set_operation_mode:
  name: Set operation mode
  description: Set operation mode of heating circuit
  fields:
    mode:
      name: Heating Operation Mode
      description: Choose whether heat pump shall heat or cool according to heating circuit target supply temperature.
      required: true
      default: "0"
      selector:
        select:
          mode: Dropdown
          options:
            - value: "0"
              label: "Heating"
            - value: "1"
              label: "Cooling"

set_heating_mode:
  name: Set heating mode
  description: Set mode of heating circuit
  fields:
    mode:
      name: Heating Mode
      description: Find the description of the values in the Solarfocus manual
      mode: Dropdown
      required: true
      default: "3"
      selector:
        select:
          options:
            - value: "0"
              label: "Dauerbetrieb"
            - value: "1"
              label: "Absenkbetrieb"
            - value: "2"
              label: "Automatik (Zeiteinstellung wird beachtet)"
            - value: "3"
              label: "Heizkreis ausgeschaltet (nur Frostwache)"

set_smart_grid:
  name: Set SmartGrid
  description: Set SmartGrid operation state
  fields:
    state:
      name: Smart Grid State
      description: Find the description of the values in the Solarfocus manual
      mode: Dropdown
      required: true
      default: "2"
      selector:
        select:
          options:
            - value: "2"
              label: "Normalbetrieb"
            - value: "4"
              label: "Einschaltung"
